### ISSUE TITLE
implement FREEZE action

### ISSUE THREAD

**Issue by Bebersohl** [Bebersohl/hp-redux#14]
If a minion or hero is frozen it can't perform an action for a turn.

Steps to implement `FREEZE` are roughly the same as #13 

`FREEZE` should take either a single id or an array of id's to freeze and the number of turns the target will be frozen (set a default for this argument to be 1 since it will be 1 99% of the time).  Either minion ids or hero ids are permissible.

When a minion/hero is frozen its `frozenFor` property is set to the number of turns the target(s) will be frozen for (this property will be decremented every turn).

Both the minions and heroes reducers should handle this action.

**Comment by ericebersohl** [comment]
I'll work on freeze next.

**Comment by Bebersohl** [comment]
@ericebersohl kk. Use a [rest param](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) to gather the id's for the action creator.

**Comment by ericebersohl** [comment]
@Bebersohl I'm having some trouble with this action.

Here's the action creator I'm using:
`freeze = (frozenFor =1, ...ids) => ({...`

The trouble is that I'd like to not have to explicitly list a frozen for value every time (because the default frozen time is so common), but if you simply list an arbitrary number of ids, Javascript doesn't know how to handle it.

In the tests, when I call `freeze('heroId1','heroId2') I end up with this object:
{ 
heroId2: {
  frozenFor: 'heroId1'
  }
}

**Action Creator:**
`exports.freeze = (frozenFor = 1, ...ids) => ({
  type: FREEZE,
  ids,
  frozenFor,
});`

**Reducer:**
`case FREEZE: {
      let newFreeze = {};
      action.ids.forEach((id) => {
        if (state[id] !== undefined) {
          newFreeze[id] = {
            frozenFor: action.frozenFor,
          }
        }
      });

      return merge(state, newFreeze);
    }`

Let me know if you'd rather see the code another way.

**Comment by Bebersohl** [comment]
I don't actually think there is a card that freezes a minion for longer than 1 turn. I copied the `frozenFor` property from hearthbreaker--I'm not sure why they did it this way.  Wanna just change it instead to a boolean called `frozen`? That way the action creator only needs to take in id's

**Comment by Bebersohl** [comment]
@ericebersohl OK so I talked to Kevin and it turns out I mislead you :P.

We need to use an integer for `frozenFor` because the number of turns a minion is frozen for is different depending on whether the minion was frozen on my turn or my opponents turn.  If I freeze my minion on my turn it's frozen for 2 turns and if my opponent freezes my minion it's frozen for 1 turn.

So I think the action creator should look like this:
```
(frozenFor, [ ids ])
```
No default param for frozenFor and an array of id's instead of using the rest param.

**Comment by ericebersohl** [comment]
Sounds good.  I'll make the changes.
